'use strict';

// Do this as the first thing so that any code reading it knows the right env.
process.env.BABEL_ENV = 'development';
process.env.NODE_ENV = 'development';
// Makes the script crash on unhandled rejections instead of silently
// ignoring them. In the future, promise rejections that are not handled will
// terminate the Node.js process with a non-zero exit code.
process.on('unhandledRejection', (err) => {
    throw err;
});

// Ensure environment variables are read.
require('../config/env');

const fs = require('fs');
const {spawn} = require('child_process');
const rspack = require('@rspack/core');
const {RspackDevServer} = require('@rspack/dev-server');
const paths = require('../config/paths');
const configFactory = require('../config/rspack.config');
const createDevServerConfig = require('../config/rspackDevServer.config');

const isInteractive = process.stdout.isTTY;

// Warn and crash if required files are missing
if (!checkRequiredFiles([paths.appHtml, paths.appIndexJs])) process.exit(1);

// Tools like Cloud9 rely on this.
const DEFAULT_PORT = parseInt(process.env.PORT, 10) || 3000;
const HOST = process.env.HOST || '0.0.0.0';

const config = configFactory('development');
const protocol = process.env.HTTPS === 'true' ? 'https' : 'http';

// Serve rspack assets generated by the compiler over a web server.
const serverConfig = {
    ...createDevServerConfig(),
    host: HOST,
    port: DEFAULT_PORT,
};

const compiler = rspack(config);
const devServer = new RspackDevServer(serverConfig, compiler);

// Launch RspackDevServer.
devServer.startCallback(() => {
    if (isInteractive)
        console.log('Starting the development server...\n');
    
    const url = `${protocol}://${HOST === '0.0.0.0' ? 'localhost' : HOST}:${DEFAULT_PORT}/`;
    
    openBrowser(url);
});

for (const sig of ['SIGINT', 'SIGTERM']) {
    process.on(sig, async () => {
        await devServer.stop();
        process.exit();
    });
}

// Gracefully exit when stdin ends
process.stdin.on('end', async () => {
    await devServer.stop();
    process.exit();
});

function checkRequiredFiles(files) {
    return files.every((file) => {
        if (fs.existsSync(file))
            return true;
        
        console.log(`The file ${file} does not exist.`);
        
        return false;
    });
}

function openBrowser(url) {
    const {platform} = process;
    let command;
    const args = [];
    
    if (platform === 'darwin') {
        command = 'open';
        args.push(url);
    } else if (platform === 'win32') {
        command = 'cmd';
        args.push('/c', 'start', '""', url.replace(/&/g, '^&'));
    } else {
        command = 'xdg-open';
        args.push(url);
    }
    
    const child = spawn(command, args, {
        stdio: 'ignore',
    });
    
    child.on('error', () => {});
}